[package]
name = "aoc2024-04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "04-1"
path = "pt1.rs"

[[bin]]
name = "04-2"
path = "pt2.rs"
