[package]
name = "aoc2024-03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"

[[bin]]
name = "03-1"
path = "pt1.rs"

[[bin]]
name = "03-2"
path = "pt2.rs"
