[package]
name = "aoc2024-05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "05-1"
path = "pt1.rs"

[[bin]]
name = "05-2"
path = "pt2.rs"
